name: Generate and Deploy M3U

on:
  push:
    branches:
      - main
      - gh-pages
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate M3U
        run: bash generate.sh

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Asegúrate de que 'all.m3u' esté en el directorio raíz
